name: Build Public Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig: ['0.15.0-dev.451+a843be44a']

    steps:
      - uses: actions/checkout@v3
        with:
          repository: BASIX/basix
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Install Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: ${{ matrix.zig }}

      - name: Build
        run: zig build -Doptimize=ReleaseFast

      - name: Prepare Release Files
        shell: bash
        run: |
          mkdir -p releases
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp zig-out/bin/basix.exe releases/basix-latest-windows-x86_64.exe
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            cp zig-out/bin/basix releases/basix-latest-macos-x86_64
          else
            cp zig-out/bin/basix releases/basix-latest-linux-x86_64
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/basix-latest-*
          tag_name: latest
          name: Latest Build
          body: |
            Latest build of BASIX for all platforms.
            
            ## Changes
            - Latest updates from main branch
            - Optimized builds for all platforms
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 